config: fix compilation warning
Now visible after the merge with upstream, see the parent commit:

  config.c: In function 'setenv_config':
  config.c:577:26: error: format '%d' expects argument of type 'int', but argument 3 has type 'long int' [-Werror=format=]
    577 |         sprintf(value, "%d", config->tolerance_usecs);
        |                         ~^   ~~~~~~~~~~~~~~~~~~~~~~~
        |                          |         |
        |                          int       long int
        |                         %ld

Fixes: 8465e2d ("net-test: packetdrill: implement relative time tolerance")
Fixes: c2c6037 ("packetdrill: export config into environment of scripts")
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>
(cherry picked from commit cc2e43172d6c4f27563f4f3d683efe19c85a12b1)
Signed-off-by: Matthieu Baerts (NGI0) <matttbe@kernel.org>