net-test: packetdrill: fix build issue with gcc 11
gcc 11 complains about use of deprecated pthread_yield():

cc -g -Wall -Werror   -c -o run_system_call.o run_system_call.c
run_system_call.c: In function ‘yield’:
run_system_call.c:3375:9: error: ‘pthread_yield’ is deprecated: pthread_yield is deprecated, use sched_yield instead [-Werror=deprecated-declarations]
 3375 |         return pthread_yield();
      |         ^~~~~~
In file included from /usr/include/features.h:488,
                 from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/limits.h:26,
                 from /usr/lib/gcc/x86_64-redhat-linux/11/include/limits.h:203,
                 from /usr/lib/gcc/x86_64-redhat-linux/11/include/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-redhat-linux/11/include/limits.h:34,
                 from types.h:34,
                 from run_system_call.h:28,
                 from run_system_call.c:26:
/usr/include/pthread.h:479:12: note: declared here
  479 | extern int __REDIRECT_NTH (pthread_yield, (void), sched_yield)
      |            ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [<builtin>: run_system_call.o] Error 1

replace it with sched_yield() to restore buildability.

Reported-by: Poorva Sonparote <poorva.sonparote@gmail.com>
Signed-off-by: Davide Caratti <dcaratti@redhat.com>
(cherry picked from commit 755d5affaa870c7f603d403cfd1238a35cd70a23)
Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>